// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SelfSchoolDAL.DataContext;

namespace SelfSchoolDAL.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SelfSchoolDAL.Entities.Admin", b =>
                {
                    b.Property<int>("idAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("login")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idAdmin");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("SelfSchoolDAL.Entities.Answer", b =>
                {
                    b.Property<int>("idAnswer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("fastAnswer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("gradeAnswer")
                        .HasColumnType("int");

                    b.Property<int>("idMaterial")
                        .HasColumnType("int");

                    b.Property<int>("idPupil")
                        .HasColumnType("int");

                    b.Property<int>("idTask")
                        .HasColumnType("int");

                    b.HasKey("idAnswer");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("SelfSchoolDAL.Entities.ClassSchool", b =>
                {
                    b.Property<int>("idClass")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("letterClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numberClass")
                        .HasColumnType("int");

                    b.HasKey("idClass");

                    b.ToTable("ClassSchools");
                });

            modelBuilder.Entity("SelfSchoolDAL.Entities.Family", b =>
                {
                    b.Property<int>("idFamily")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("idParent")
                        .HasColumnType("int");

                    b.Property<int>("idPupil")
                        .HasColumnType("int");

                    b.HasKey("idFamily");

                    b.ToTable("Families");
                });

            modelBuilder.Entity("SelfSchoolDAL.Entities.Lesson", b =>
                {
                    b.Property<int>("idLesson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("dateLesson")
                        .HasColumnType("bigint");

                    b.Property<int>("idTeacher")
                        .HasColumnType("int");

                    b.Property<string>("nameLesson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idLesson");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("SelfSchoolDAL.Entities.Material", b =>
                {
                    b.Property<int>("idMaterial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("fileMaterial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("urlMaterial")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idMaterial");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("SelfSchoolDAL.Entities.Parent", b =>
                {
                    b.Property<int>("idParent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("birthdayParent")
                        .HasColumnType("bigint");

                    b.Property<string>("emailParent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("loginParent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nameParent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("passwordParent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phoneParent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("surnameParent")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idParent");

                    b.ToTable("Parents");
                });

            modelBuilder.Entity("SelfSchoolDAL.Entities.Pupil", b =>
                {
                    b.Property<int>("idPupil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("birthdayPupil")
                        .HasColumnType("bigint");

                    b.Property<string>("emailPupil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idClass")
                        .HasColumnType("int");

                    b.Property<string>("loginPupil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("namePupil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("passwordPupil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phonePupil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("surnamePupil")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idPupil");

                    b.ToTable("Pupils");
                });

            modelBuilder.Entity("SelfSchoolDAL.Entities.TaskLesson", b =>
                {
                    b.Property<int>("idTask")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("dateTask")
                        .HasColumnType("bigint");

                    b.Property<string>("descriptionTask")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idLesson")
                        .HasColumnType("int");

                    b.Property<int>("idMaterial")
                        .HasColumnType("int");

                    b.Property<string>("nameTask")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idTask");

                    b.ToTable("TaskLessons");
                });

            modelBuilder.Entity("SelfSchoolDAL.Entities.Teacher", b =>
                {
                    b.Property<int>("idTeacher")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("birthdayTeacher")
                        .HasColumnType("bigint");

                    b.Property<string>("emailTeacher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("loginTeacher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nameTeacher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("passwordTeacher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phoneTeacher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("subjectTeacher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("surnameTeacher")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idTeacher");

                    b.ToTable("Teachers");
                });
#pragma warning restore 612, 618
        }
    }
}
